add tests for modifyplan and move messages out of test file
KTH/lms-functions pull request #24
Opened 2024-08-29 08:08 UTC by Epicpants-kth

2024-08-29 08:40 UTC, jhsware requested changes
Outstanding scope, lite fix kvar IMHO

2024-08-29 08:40 UTC, jhsware commented on RegisteredStudent/index.test.ts
> +const modifyPositionInPlan = fs.readFileSync('ProgramStudent/__fixtures__/events/05_membershop_courseOffering_ModifyPositionInPlan.xml', { encoding: 'utf8', flag: 'r' });
Jag tycker att det var bättre som i övriga där man läser in filen i själva testfunktionen. Tekniskt innebär det dessutom att garbage collection sker när funktionen körts klart istället för när appen stänger ner.

2024-08-29 08:40 UTC, jhsware commented on RegisteredStudent/mockContext.ts
> +      };
Om inte de här används/behövs tycker jag att du kan ta bort dem. Isf även definitionen ovan.

2024-08-29 08:40 UTC, jhsware commented on package.json
> +    "fs": "^0.0.1-security"
fs är en del av Node så den här paketet ska bort. Jag föreslår att du även ändrar importerna till `import fs from "node:fs";` för att säkra att man inte installerar ett (potentiellt skadligt) paket.

2024-08-29 08:40 UTC, jhsware commented on RegisteredStudent/index.test.ts
> +jest.spyOn(canvasApi, 'sendEnrollments').mockResolvedValue({ sisImportId: 1234 });
Jag tror jest.fn() är bättre så att testet inte anropar Canvas
https://medium.com/javascript-journal-unlocking-project-potential/jest-fn-vs-jest-spyon-understanding-the-differences-for-effective-testing-0f5928f7a411

2024-08-29 12:37 UTC, Epicpants-kth commented on RegisteredStudent/index.test.ts
> +jest.spyOn(canvasApi, 'sendEnrollments').mockResolvedValue({ sisImportId: 1234 });
Jag använder nu jest.fn() men det var klurigt att få till ett mockat response. provat en del olika lösningar, har du något förslag?

2024-08-30 06:19 UTC, jhsware requested changes

2024-08-30 06:19 UTC, jhsware commented on RegisteredStudent/index.test.ts
> +    sendEnrollments: jest.fn(() => {return {sis_import: 1234}})
Byt till:
`
jest.fn((enrollment, context) => ({ enrollment, context }))
`

så kommer du kunna köra:

`
expect(result).toMatchSnapshot();
`

Och då kontrollerar du att output faktiskt blir det som man förväntar sig.

2024-08-30 08:57 UTC, merged